/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  WMGLApp as WmglApp
} from './components/wmgl-app/wmgl-app';

declare global {
  interface HTMLWmglAppElement extends WmglApp, HTMLElement {
  }
  var HTMLWmglAppElement: {
    prototype: HTMLWmglAppElement;
    new (): HTMLWmglAppElement;
  };
  interface HTMLElementTagNameMap {
    "wmgl-app": HTMLWmglAppElement;
  }
  interface ElementTagNameMap {
    "wmgl-app": HTMLWmglAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "wmgl-app": JSXElements.WmglAppAttributes;
    }
  }
  namespace JSXElements {
    export interface WmglAppAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  WMGLMap as WmglMap
} from './components/wmgl-map/wmgl-map';

declare global {
  interface HTMLWmglMapElement extends WmglMap, HTMLElement {
  }
  var HTMLWmglMapElement: {
    prototype: HTMLWmglMapElement;
    new (): HTMLWmglMapElement;
  };
  interface HTMLElementTagNameMap {
    "wmgl-map": HTMLWmglMapElement;
  }
  interface ElementTagNameMap {
    "wmgl-map": HTMLWmglMapElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "wmgl-map": JSXElements.WmglMapAttributes;
    }
  }
  namespace JSXElements {
    export interface WmglMapAttributes extends HTMLAttributes {
      latitude?: number;
      longitude?: number;
      maxzoom?: number;
      minzoom?: number;
      zoom?: number;
    }
  }
}


import {
  WMGLStyle as WmglStyle
} from './components/wmgl-style/wmgl-style';

declare global {
  interface HTMLWmglStyleElement extends WmglStyle, HTMLElement {
  }
  var HTMLWmglStyleElement: {
    prototype: HTMLWmglStyleElement;
    new (): HTMLWmglStyleElement;
  };
  interface HTMLElementTagNameMap {
    "wmgl-style": HTMLWmglStyleElement;
  }
  interface ElementTagNameMap {
    "wmgl-style": HTMLWmglStyleElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "wmgl-style": JSXElements.WmglStyleAttributes;
    }
  }
  namespace JSXElements {
    export interface WmglStyleAttributes extends HTMLAttributes {
      url?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
